FACENET_BATCH_SIZE = 128
IMAGE_SIZE_MOBILENET = 224

MLP_CLASSIFIER_HIDDEN_SIZE = 256
MLP_CLASSIFIER_BATCH_SIZE = 128
MLP_CLASSIFIER_NUM_EPOCHS = 50

MLP_KERAS_INPUT_NAME = "features"
MLP_KERAS_OUTPUT_NAME = "probabilities"

MOBILENET_INPUT_NAME = "images"
MOBILENET_OUTPUT_NAME = "features"

PRED_THRESHOLD_SSD = 0.80