FACENET_TRAIN_BATCH = 32
FACENET_IMAGE_SIZE = 96

MLP_CLASSIFIER_HIDDEN_SIZE = 256
MLP_CLASSIFIER_BATCH_SIZE = 256
MLP_CLASSIFIER_NUM_EPOCHS = 600

MLP_KERAS_INPUT_NAME = "features"
MLP_KERAS_OUTPUT_NAME = "probabilities"

COREML_IMAGES_NAME = "images"
COREML_FEATURES_NAME = "features"
COREML_INPUT_SCALE = 1 / 255.0

IMAGE_SIZE_MOBILENET = 224
MOBILENET_RED_BIAS = -0.48502
MOBILENET_GREEN_BIAS = -0.45796
MOBILENET_BLUE_BIAS = -0.40761

MOBILENET_TRAIN_BATCH = 128

PRED_THRESHOLD_SSD = 0.80