EXTENSION_H5 = ".h5"
EXTENSION_JPG = ".jpg"
EXTENSION_COREML = ".mlmodel"

JSON_KEY_EMBEDDINGS = "embedding"
JSON_KEY_LABEL = "label"

FILENAME_LABELS = "labels.txt"

SUBFOLDER_NAME_CHECK_IN = "check_in"
SUBFOLDER_NAME_FACES = "faces"

FEATURE_DIMEN_FACENET = 128
FEATURE_DIMEN_MOBILENET = 1024